### ISSUE TITLE
getImageData will be too slow when be called in a big loop

### ISSUE THREAD

**Issue by wethk** [bfred-it/get-canvas-pixel-color#2]
getImageData will be too slow when be called in a big loop

code is below:
`
const width = 1000;
const height = 750;

    for (var i = 0; i < width; i++) {
        for (var j = 0; j < height; j++) {
            let { a, r, g, b } = getCanvasPixelColor(ctx, i, j);
            if (a) {
                left = i;
                msg = `${a}-${r}-${g}-${b}`;
                break;
            }
        }
        if (left) { break; }
    }
`

code is every easy,if you run directly,it will take u 3 min. but if you debugger inside the loop some times.it will return result at once.
so strange.

**Comment by fregante** [comment]
`getCanvasPixelColor` is just for one pixel. If you want to get the whole image, it's best your use the underlying API directly because it will let you read multiple pixels at once:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData

**Comment by wethk** [comment]
thx, u are right, API of canvas is actually async func，the cost of UI layer API is more bigger than data handler
